# Site
name: "Pig"
description: "Jared \"Pig\" Krensel"
meta_description: "Jared \"Pig\" Krensel"
logo: 'assets/images/logo_pig_400.jpg'
baseurl: /pig
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://test'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
